name: tensorfit
description: Tensorfit fitness application.

version: 1.0.0+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  image: ^2.1.12  

  web_socket_channel: ^1.1.0

  flutter_svg: ^0.17.3+1

  flutter_bloc: ^3.0.0

  equatable: ^1.0.1

  shared_preferences: ^0.5.4

  intl: ^0.16.0

  firebase_auth: ^0.15.5+3

  google_sign_in: ^4.2.0

  flutter_facebook_login: ^3.0.0

  apple_sign_in: ^0.1.0

  dots_indicator: ^1.0.0

  flutter_picker: ^1.1.0

  flutter_slidable: ^0.5.3


  #cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  camera: ^0.5.7+5
  
  tflite: 1.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.svg
    - assets/login/facebook.svg
    - assets/login/google.svg
    - assets/login/apple.svg
    - assets/journey/bg.svg
    - assets/journey/next_active.svg
    - assets/journey/next_inactive.svg
    - assets/map/levels/left/1.png
    - assets/map/levels/left/2.png
    - assets/map/levels/left/3.png
    - assets/map/levels/left/4.png
    - assets/map/levels/left/5.png
    - assets/map/levels/left/6.png
    - assets/map/levels/left_h/1.png
    - assets/map/levels/left_h/2.png
    - assets/map/levels/left_h/3.png
    - assets/map/levels/left_h/4.png
    - assets/map/levels/left_h/5.png
    - assets/map/levels/left_h/6.png
    - assets/map/levels/right/1.png
    - assets/map/levels/right/2.png
    - assets/map/levels/right/3.png
    - assets/map/levels/right/4.png
    - assets/map/levels/right/5.png
    - assets/map/levels/right/6.png
    - assets/map/levels/right_h/1.png
    - assets/map/levels/right_h/2.png
    - assets/map/levels/right_h/3.png
    - assets/map/levels/right_h/4.png
    - assets/map/levels/right_h/5.png
    - assets/map/levels/right_h/6.png
    - assets/map/stars_0.svg
    - assets/map/stars_1.svg
    - assets/map/stars_2.svg
    - assets/map/stars_3.svg
    - assets/map/marker_left.svg
    - assets/map/marker_right.svg
    - assets/posenet_mv1_075_float_from_checkpoints.tflite