name: tensorfit
description: Tensorfit fitness application.

version: 1.0.0+4

environment:
  sdk: ">=2.7.0 <3.14.0"

dependencies:
  ml_linalg: ^12.17.2

  flutter:
    sdk: flutter

  image: ^3.0.0 

  web_socket_channel: ^2.0.0

  flutter_svg: ^0.21.0

  flutter_bloc: ^3.0.0

  equatable: ^1.0.1

  shared_preferences: ^0.5.4

  after_layout: ^1.0.7+2

  intl: ^0.16.0

  google_sign_in: ^4.2.0

  flutter_facebook_login: ^3.0.0

  apple_sign_in: ^0.1.0

  dots_indicator: ^1.2.0

  flutter_picker: ^1.1.0

  flutter_slidable: ^0.5.6

  video_player: ^1.0.1
  
  vptree: ^0.1.0

  http: ^0.13.0

  firebase_core: ^1.4.0

  cloud_firestore: ^2.4.0


  #cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  camera: ^0.5.7+5
  
  tflite: 1.1.1

  test: ^1.16.4

  flutter_launcher_icons: ^0.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.svg
    - assets/login/facebook.svg
    - assets/login/google.svg
    - assets/login/apple.svg
    - assets/journey/bg.svg
    - assets/journey/next_active.svg
    - assets/journey/next_inactive.svg
    - assets/map/levels/left/1.png
    - assets/map/levels/left/2.png
    - assets/map/levels/left/3.png
    - assets/map/levels/left/4.png
    - assets/map/levels/left/5.png
    - assets/map/levels/left/6.png
    - assets/map/levels/right/1.png
    - assets/map/levels/right/2.png
    - assets/map/levels/right/3.png
    - assets/map/levels/right/4.png
    - assets/map/levels/right/5.png
    - assets/map/levels/right/6.png
    - assets/map/stars_0.svg
    - assets/map/stars_1.svg
    - assets/map/stars_2.svg
    - assets/map/stars_3.svg
    - assets/map/marker_left.svg
    - assets/map/marker_right.svg
    - assets/posenet_mv1_075_float_from_checkpoints.tflite
    - assets/video.mp4
    - assets/journey.png
    - assets/backgroundEndOfExercises.png
    - assets/tutorialExercises/squats.gif
    - assets/tensor-logo.png
    - assets/icon/icon_account.png
    - assets/icon/icon_eye.png
    - assets/icon/icon_account_1_pur.png
    - assets/icon/icon_eye_1_pur.png
    - assets/icon/icon_account_2_pur.png
    - assets/icon/icon_eye_2_pur.png
    - assets/icon/main_icon.jpg
    - assets/backgr.jpg
    - assets/tensorfit_demo.mp4
    - assets/imgLevelPage/img_1.png
    - assets/imgLevelPage/img_2.png
    - assets/tutorPageBackgr.png
    - assets/genderPage/man.png
    - assets/genderPage/manRed.png
    - assets/genderPage/woman.png
    - assets/genderPage/womanRed.png

flutter_icons:
   android: "launcher_icon"
   ios: true
   image_path: "assets/icon/main_icon.jpg"